//
// Created by theownage on 20/03/2026.
//

#ifndef ARKANOID_CONFIG_H
#define ARKANOID_CONFIG_H

#define WINDOW_WIDTH 800
#define WINDOW_HEIGHT 600
#define TARGET_FPS 60

#define PLAYER_WIDTH 75
#define PLAYER_HEIGHT 15
#define PLAYER_COLOR BLUE
#define PLAYER_SPEED 500
#define PLAYER_DEFAULT_Y_OFFSET 20
#define PLAYER_UPPER_BOUND 500

// DEV TOOLS GUI
#define DEV_GUI_HEIGHT 40
#define OFFSET_Y_DEV_GUI 10
#define OFFSET_X_DEV_GUI_FPS 20

// GAME LOGIC
enum GameState {
    STATE_MENU,
    STATE_PLAYING,
    STATE_PAUSED,
    STATE_LEVEL_CLEAR,
    STATE_GAME_OVER
};

// GAME MENU
#define TITLE_SCREEN_X (WINDOW_WIDTH / 2)
#define TITLE_SCREEN_Y (WINDOW_HEIGHT / 2)

#endif //ARKANOID_CONFIG_H